micronaut:
  application:
    name: open-event
  security:
    enabled: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/openevent
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: none
    dialect: POSTGRES


flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      schemas: open_event
      default-schema: open_event
      clean-schema: true
