micronaut:
  application:
    name: open-event
  server:
    port: 8080
    thread-selection: AUTO
  data:
    pageable:
      max-page-size: 1000
  http:
    client:
      read-timeout: 20s
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/openevent
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      clean-schema: true

jackson:
  bean-introspection-module: true
  serialization-inclusion: NON_NULL

